// Generated by https://quicktype.io

export interface MedicinesResponse {
    ok:             boolean;
    page:           string;
    totalPages:     number;
    totalMedicines: number;
    medicines:      Medicine[];
}

export interface Medicine {
    name:         string;
    ch:           string;
    medicines?:    Medicine[];
    type?:         MedicineType;
    _id:           string;
    prescription?: Prescription[];
    description?: string;
}

export interface MedicineResponse {
    ok:       boolean;
    medicine: Medicine;
}

export interface UpdatePrescriptionResponse {
    prescription: Prescription;
}

export interface Prescription {
    _id:         string;
    description: string;
    createdAt?:   string;
    updatedAt?:   string;
}


export enum MedicineType {
    FORMULA = 'formula',
    MEDICINE = 'medicine'
}



